name: sqflite_test_app
description: sqflite test application.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1

environment:
  sdk: ^3.7.0

dependencies:
  # analyzer: '>=5.2.0'
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: '>=0.1.3'
  sqflite: '>=2.0.0-nullsafety.2'
  sqflite_common_ffi:
  sqflite_common_ffi_async:
  flutter_web_plugins:
    sdk: flutter
  path_provider:
  sqflite_common:
  dev_build:
  process_run: '>=0.13.3-1'
  path:
  sqflite_common_ffi_web:
  sqlite3: '>=2.4.6'
  sqflite_example_common:
    git:
      url: https://github.com/tekartik/sqflite
      ref: dart3a
      path: packages_flutter/sqflite_example_common
  sqflite_common_test:
    path: ../sqflite_common_test
  test: '>=1.16.0-nullsafety.10'
dev_dependencies:
  flutter_lints: ">=5.0.0"
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  pub_semver:
  sqlite3_flutter_libs:
  sqflite_support:
    path: ../sqflite_support
dependency_overrides:
  sqflite:
    path: ../sqflite
  sqflite_darwin:
    path: ../sqflite_darwin
  sqflite_android:
    path: ../sqflite_android
  sqflite_platform_interface:
    path: ../sqflite_platform_interface
  sqflite_common:
    path: ../sqflite_common
  sqflite_common_ffi:
    path: ../sqflite_common_ffi
  sqflite_common_ffi_web:
    path: ../packages_web/sqflite_common_ffi_web
  sqflite_common_ffi_async:
    path: ../packages/sqflite_common_ffi_async
  sqflite_example_common:
    path: ../packages_flutter/sqflite_example_common
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

